theme: jekyll-theme-cayman
title: Optimum Path Planning for Arbitrary Mazes
description: > 
  Hill Balliet and Simon Posada Fishman. 
  HMC <i>Autonomous Robot Navigation</i> Spring 2018
show_downloads: true
